# fly.toml app configuration file generated for marketing-tut on 2024-01-18T22:44:13-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "marketing-tut"
primary_region = "mia"

[env]
PORT = "3000"
SHOPIFY_APP_URL = "https://my-app.fly.dev"
SHOPIFY_API_KEY = "efdcaa31c727bf83cfabf0b36034b270"
SCOPES = "write_products,read_customers,write_customers"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
